using Hikaria.Core.SourceGenerators.Internal;
using System.Collections.Generic;
using System.Text;

namespace Hikaria.Core.SourceGenerators.Emitters;

internal static class CompanionEmitter
{
    public static string Emit(string @namespace, IReadOnlyList<string> typeChain, IReadOnlyList<HookInfo> hooks)
    {
        var sb = new StringBuilder(2048);
        EmitHeader(sb);
        EmitNamespaceOpen(sb, @namespace);
        EmitTypeChainOpen(sb, typeChain);

        foreach (var hook in hooks)
        {
            EmitHookMembers(sb, hook);
        }

        EmitContainerAggregators(sb, hooks);

        EmitTypeChainClose(sb, typeChain);
        EmitNamespaceClose(sb, @namespace);
        return sb.ToString();
    }

    private static void EmitHeader(StringBuilder sb)
    {
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by Hikaria.Core.SourceGenerators.NativeDetourGenerator");
        sb.AppendLine("#nullable disable");
        sb.AppendLine("#pragma warning disable CS8019  // unused usings");
        sb.AppendLine();
    }

    private static void EmitNamespaceOpen(StringBuilder sb, string ns)
    {
        if (!string.IsNullOrEmpty(ns))
            sb.Append("namespace ").Append(ns).AppendLine().AppendLine("{");
    }

    private static void EmitNamespaceClose(StringBuilder sb, string ns)
    {
        if (!string.IsNullOrEmpty(ns))
            sb.AppendLine("}");
    }

    private static void EmitTypeChainOpen(StringBuilder sb, IReadOnlyList<string> chain)
    {
        for (int i = 0; i < chain.Count; i++)
        {
            sb.Append("    unsafe partial class ").Append(chain[i]).AppendLine().AppendLine("    {");
        }
    }

    private static void EmitTypeChainClose(StringBuilder sb, IReadOnlyList<string> chain)
    {
        for (int i = chain.Count - 1; i >= 0; i--)
            sb.AppendLine("    }");
    }

    private const string HandleType = "global::Hikaria.Core.Detour.NativeDetourHandle";
    private const string DescriptorType = "global::Hikaria.Core.Detour.DetourDescriptor";
    private const string NativeDetourType = "global::Hikaria.Core.Detour.NativeDetour";
    private const string TypeArrayType = "global::System.Type";
    private const string UnmanagedFunctionPointerAttr = "global::System.Runtime.InteropServices.UnmanagedFunctionPointerAttribute";
    private const string CallingConvCdecl = "global::System.Runtime.InteropServices.CallingConvention.Cdecl";

    private static void EmitHookMembers(StringBuilder sb, HookInfo h)
    {
        var stem = h.Stem;

        sb.Append("        [").Append(UnmanagedFunctionPointerAttr).Append('(').Append(CallingConvCdecl).AppendLine(")]");
        sb.Append("        private delegate ").Append(h.ReturnTypeSyntax).Append(' ').Append(stem).Append("_HookDelegate(");
        EmitParamList(sb, h.Parameters);
        sb.AppendLine(");");
        sb.AppendLine();

        sb.Append("        private static readonly ").Append(HandleType).Append('<').Append(stem).Append("_HookDelegate> ");
        sb.Append(stem).Append("_Handle = ").Append(NativeDetourType).Append(".Create<").Append(stem).Append("_HookDelegate>(").AppendLine();
        sb.Append("            new ").Append(DescriptorType).AppendLine();
        sb.AppendLine("            {");
        sb.Append("                Type        = typeof(").Append(h.TargetDeclaringTypeSyntax).AppendLine("),");
        sb.Append("                MethodName  = \"").Append(h.TargetMethodNameOrCtor).AppendLine("\",");
        sb.Append("                ReturnType  = typeof(").Append(EmitDescriptorReturnType(h)).AppendLine("),");
        sb.Append("                ArgTypes    = new ").Append(TypeArrayType).Append("[] { ");
        EmitDescriptorArgTypes(sb, h);
        sb.AppendLine(" },");
        sb.Append("                IsGeneric   = ").Append(h.TargetTypeArgumentSyntax.IsEmpty ? "false" : "true").AppendLine(",");
        if (!h.TargetTypeArgumentSyntax.IsEmpty)
        {
            sb.Append("                GenericTypeArguments = new ").Append(TypeArrayType).Append("[] { ");
            var first = true;
            foreach (var ta in h.TargetTypeArgumentSyntax)
            {
                if (!first) sb.Append(", ");
                sb.Append("typeof(").Append(ta).Append(')');
                first = false;
            }
            sb.AppendLine(" },");
        }
        sb.AppendLine("            },");
        sb.Append("            ").Append(h.HookMethodName).AppendLine(");");
        sb.AppendLine();

        sb.Append("        private static ").Append(stem).Append("_HookDelegate ").Append(stem)
          .Append("_Original => ").Append(stem).AppendLine("_Handle.Original;");
        sb.AppendLine();

        sb.Append("        public static bool ").Append(stem).Append("_Apply() => ").Append(stem).AppendLine("_Handle.Apply();");
        sb.Append("        public static void ").Append(stem).Append("_Dispose() => ").Append(stem).AppendLine("_Handle.Dispose();");
        sb.AppendLine();
    }

    private static void EmitContainerAggregators(StringBuilder sb, IReadOnlyList<HookInfo> hooks)
    {
        sb.AppendLine("        public static void ApplyAll()");
        sb.AppendLine("        {");
        foreach (var h in hooks)
            sb.Append("            ").Append(h.Stem).AppendLine("_Apply();");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        public static void DisposeAll()");
        sb.AppendLine("        {");
        foreach (var h in hooks)
            sb.Append("            ").Append(h.Stem).AppendLine("_Dispose();");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void EmitParamList(StringBuilder sb, EquatableArray<ParamInfo> ps)
    {
        var first = true;
        foreach (var p in ps)
        {
            if (!first) sb.Append(", ");
            sb.Append(p.TypeSyntax).Append(' ').Append(p.Name);
            first = false;
        }
    }

    private static string EmitDescriptorReturnType(HookInfo h)
        => h.TargetMember == NativeDetourMember.Constructor ? "void" : h.ReturnTypeSyntax;

    private static void EmitDescriptorArgTypes(StringBuilder sb, HookInfo h)
    {
        int start = h.TargetIsStatic ? 0 : 1;
        int end = h.Parameters.Length - 1;
        var first = true;
        for (int i = start; i < end; i++)
        {
            if (!first) sb.Append(", ");
            sb.Append("typeof(").Append(h.Parameters[i].TypeSyntax).Append(')');
            first = false;
        }
    }
}
